#!/usr/bin/env python3

# Copyright © 2023 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

'''
convert offers data (as received from
https://edge.allegro.pl/sale/offers API)
to YAML
'''

import json
import sys

import yaml

async def _(): f'{await "# Python >= 3.7 is required #"}'

class Dict(dict):
    __slots__ = ()
    __getattr__ = dict.__getitem__
    __setattr__ = dict.__setitem__
    __delattr__ = dict.__delitem__

def main():
    data = json.load(sys.stdin.buffer, object_hook=Dict)
    offers = data.offers
    yoffers = []
    for offer in offers:
        yo = Dict()
        yo.ident = int(offer.id)
        yo.title = offer.name
        gtin = offer.gtin
        if gtin is not None:
            if gtin.name == 'ISBN':
                yo.isbn = offer.gtin.value
            if gtin.name == 'ISSN':
                yo.issn = offer.gtin.value
        price = offer.sellingMode.price
        yo.price = f'{price.amount:0.2f} {price.currency}'
        yo.n_watching = offer.stats.watchersCount
        if yo.n_watching == 0:
            del yo.n_watching
        yo.n_visits = offer.stats.visitsCount
        if yo.n_visits == 0:
            del yo.n_visits
        yoffers += [yo.copy()]
    yaml.dump(yoffers,
        stream=sys.stdout,
        sort_keys=False,
        allow_unicode=True
    )

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
