#!/usr/bin/env python3

# Copyright © 2021-2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

'''
convert offers page
(copy&pasted from <https://allegro.pl/moje-allegro/sprzedaz/moje-oferty>)
to YAML
'''

import decimal
import sys
import types

import yaml

0_0  # Python >= 3.6 is required

def main():
    stdin = map(str.rstrip, sys.stdin)
    for line in stdin:
        if line == 'status':
            break
    lst = []
    while True:
        ns = types.SimpleNamespace()
        title = next(stdin)
        tmp = next(stdin)
        if title.isdigit() and tmp[0] == '1' and tmp[1] == '-':
            break
        if tmp.isdigit():
            ident = tmp
        else:
            assert title == tmp
            ident = next(stdin)
        ns.ident = int(ident)
        ns.title = title
        count = next(stdin)
        if count == 'Produkt:':
            count = next(stdin)
        if count != '-':
            count = int(count)
            if count != 1:
                ns.count = count
        tmp = next(stdin)
        assert tmp == ''
        price = next(stdin)
        assert price.endswith(' zł')
        price = price[:-3]
        price = price.replace(',', '.')
        price = decimal.Decimal(price)
        ns.price = f'{price} PLN'
        tmp = next(stdin)
        if tmp == 'Przegląd cen':
            n_sold = next(stdin)
        else:
            n_sold = tmp
        if n_sold != '-':
            ns.n_sold = int(n_sold)
        n_watching = next(stdin)
        if n_watching != '-':
            n_watching = int(n_watching)
            if n_watching > 0:
                ns.n_watching = n_watching
        n_visits = next(stdin)
        if n_visits != '-':
            n_visits = int(n_visits)
            if n_visits > 0:
                ns.n_visits = n_visits
        status = next(stdin)
        status = {
            'aktywna': 'active',
            'szkic': 'draft',
            'zakończona': 'closed',
        }[status]
        if status != 'active':
            ns.status = status
        tmp = next(stdin)
        assert tmp == 'SZCZEGÓŁY'
        d = {
            k: v
            for k, v in vars(ns).items()
            if k[0] != '_'
        }
        lst += [d]
    yaml.dump(lst,
        stream=sys.stdout,
        sort_keys=False,
        allow_unicode=True
    )

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
