name: CI
on:
- push
- pull_request
jobs:
  main:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        python:
        - '3.6'
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11-dev'
        os: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{matrix.python}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python}}
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v .
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes .
    - name: install lxml
      run: |
        python3 -m pip install lxml
    - name: smoke test
      run: |
        ./mail-filter < /dev/null

# vim:ts=2 sts=2 sw=2 et
